### ISSUE TITLE
robsd-release.sh fails on armv7

### ISSUE THREAD

**Issue by moritzbuhl** [mptre/robsd#2]
armv7 does not have a unconfig target in `/usr/src/distrib/armv7/Makefile`.

```
     23 make -C "${BSDSRCDIR}/distrib/$(machine)" unconfig
```

hppa and macppc have the target but they only do `cd ramkdisk && make` and fail there to my understanding.

It might make sense to fix this in src.

**Comment by mptre** [comment]
> On 15 Apr 2023, at 10:06, Moritz Buhl ***@***.***> wrote:
> 
> ﻿
> armv7 does not have a unconfig target in /usr/src/distrib/armv7/Makefile.
> 
>      23 make -C "${BSDSRCDIR}/distrib/$(machine)" unconfig
> hppa and macppc have the target but they only do cd ramkdisk && make and fail there to my understanding.
> 
> It might make sense to fix this in src.
> 
Since unconfig is only relevant when resuming failed builds, I think it’s safe to ignore errors here as in make … || :
